version: '3.9'

services:
  app:
    build: .
    ports:
      - '9000:9000'
      - '5000:5000'
    environment:
      - TZ=Europe/Copenhagen
    labels:
      - traefik.enable=true
      - traefik.http.routers.msn.entrypoints=web
      - traefik.http.routers.msn.rule=(Host(`secu07.itu.dk`) && PathPrefix(`/`))
        #- traefik.http.middlewares.msn.stripprefix.prefixes=/mysecretnotes
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
